# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v0251 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.25.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.25.1/baywatchdog_0.25.1_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d60c75f619e621977f9976b7d02914c6c0184cb44ea76674d9f2555490e70bdc"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.25.1/baywatchdog_0.25.1_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "efb8963f590a86b81dd86ee2a14bd7a0a5d100ee2d79422bf3b36549c439636e"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.25.1/baywatchdog_0.25.1_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a1421b6aef566ded8d051de66c0b12d493633a61666c2a9208733ebcafb2cfa0"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.25.1/baywatchdog_0.25.1_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "870c2e3180cbf4ef1f6a20d07afecaf840c1b95a9a60788c25445b938600974e"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end
end
