# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v0220 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.22.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.22.0/baywatchdog_0.22.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d018574a917b5f1794fe713d254ceece69cf9fee4e5d6c427a37d30866cd24d4"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.22.0/baywatchdog_0.22.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a1551e3511b36049d422f42de0652b74ea08f07fa5220cc35af23c208336b2d8"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.22.0/baywatchdog_0.22.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c2415fafd16e4114c9303af990fdf23b9cff7958ec7f310a0ceaeb120e3a331a"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.22.0/baywatchdog_0.22.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "cc6ea3408113955a3cac66ee93db98b469da8803f1899ee6fb92f09cbbf688f1"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end
end
