# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class BaywatchAT016 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatch"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatch/releases/download/v0.1.6/baywatch_0.1.6_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e1f8cf4b4747cd70c4e5cf771ea1b55b39d9babd8ad9a6f5935f132b95529d23"

      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatch/releases/download/v0.1.6/baywatch_0.1.6_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0c93287714757d50ac8fd03d5251e3be44a21bcec05d4be6e225725f31f6efa0"

      def install
        bin.install "baywatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.1.6/baywatch_0.1.6_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b843fefdda7d1cd9e7055434338bd788d20c8aa24871c7ce0ecfd5021ca1fde2"

      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatch/releases/download/v0.1.6/baywatch_0.1.6_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f9c55d8271da4cd1c30191e54af761cef8af84cd24db3ac5ee53764d58aa62d2"

      def install
        bin.install "baywatch"
      end
    end
  end
end
