# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v011 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.1.1/baywatchdog_0.1.1_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c5e8d9c10c3cd42234dcb7872904e62c2d26262687dea22283713388faeaad6b"

      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.1.1/baywatchdog_0.1.1_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "bd74f06e24fb78c37b1fd2dffb29c2969995ce5e5970b34b3c045792b1102d01"

      def install
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/padok-team/baywatchdog/releases/download/v0.1.1/baywatchdog_0.1.1_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "f3a9b37e019ddd09cb7637a2d33c907fce7e232ce1357b7ab524761c612a38ef"

        def install
          bin.install "baywatchdog"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/padok-team/baywatchdog/releases/download/v0.1.1/baywatchdog_0.1.1_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "407141c9de4c9e67e745dd60f81566925d442586ac38474f274d47d629fde820"

        def install
          bin.install "baywatchdog"
        end
      end
    end
  end
end
