# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v061 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.6.1/baywatchdog_0.6.1_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "be94e1773e6a1a84cc7660d54c8dac5de18b33a5fd4ecfffaf80903e7d37b2b2"

      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.6.1/baywatchdog_0.6.1_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1840b852a34bea73142406fdcf4c0ca2a0b52b580f228fc93916a6707d8e53f9"

      def install
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.6.1/baywatchdog_0.6.1_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e58338a65063c28f02a2af22a31a9399bdb4fa8b4bd06014be52a27b79eb2bcb"
      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.6.1/baywatchdog_0.6.1_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ca64cb2a85b6e1e938f630ece44727225818efbef853bac2eb3b5fb2d0688115"
      def install
        bin.install "baywatchdog"
      end
    end
  end
end
