# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class BaywatchAT061 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatch"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatch/releases/download/v0.6.1/baywatch_0.6.1_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "17566e963cde86daac4740b5be6300d757669bba39d936081719882133780cfe"

      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatch/releases/download/v0.6.1/baywatch_0.6.1_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "da5dac33c29899e9b41fb5721854756070837461c9e51c13c2720091b8c7a39f"

      def install
        bin.install "baywatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.6.1/baywatch_0.6.1_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "122df2452521d5a21d9b6b6ace4b2e5792c479d7ccd85f65b1650c5f71f6f51c"
      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.6.1/baywatch_0.6.1_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "50dbdc111ba4086006afa24b6fd43ff153949273b2ac536459d54922644b00f9"
      def install
        bin.install "baywatch"
      end
    end
  end
end
