# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class BaywatchAT055 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatch"
  version "0.5.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatch/releases/download/v0.5.5/baywatch_0.5.5_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "cfc7505f3fdb96bf67ee29c331f00030fa7aca7aaf570cff2c31f561d5c622d7"

      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatch/releases/download/v0.5.5/baywatch_0.5.5_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5837d44990607ea64a57b99216637c2f8b49db603fc369bb2c4a582417db3051"

      def install
        bin.install "baywatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.5.5/baywatch_0.5.5_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1472c19ec22612f3abb814a093831d0777249749a8ab71eb9e0ca2ed19464943"
      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.5.5/baywatch_0.5.5_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3d0742ac0b4282bb3d098af3fafdeb293a0a2284d619bc05378b10862589f951"
      def install
        bin.install "baywatch"
      end
    end
  end
end
