# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v0150 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.15.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.15.0/baywatchdog_0.15.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "aa197656cb4b393701a40ef48deaa5a4c2d6269037687f52b04a95f9c8c85b23"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.15.0/baywatchdog_0.15.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "47a5eb3277da1d5d767d70300c851f0d47273ea5aefea441ad1a90af0604da17"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.15.0/baywatchdog_0.15.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "195ce43ee13348bf81e941187a72eba2bb4d4bcc73b9512ae55b635b6def4756"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.15.0/baywatchdog_0.15.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8773e84a67495f2acef8dc2db9d419ddd31a265d83baf9a77877dccab253bd01"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end
end
