# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class BaywatchAT0100 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatch"
  version "0.10.0"

  depends_on "aws-vault"
  depends_on "awscli"
  depends_on "azure-cli"
  depends_on "jq"
  depends_on "kubernetes-cli"
  depends_on "scw"
  depends_on "sshuttle"
  depends_on "yq"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatch/releases/download/v0.10.0/baywatch_0.10.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a6de2735f94c8bc974bf8f437d7bb58b267272a90c4ca562feb7a36db1cef483"

      define_method(:install) do
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatch/releases/download/v0.10.0/baywatch_0.10.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4561828d06f607023ab2b8855836eaaefe5722d698100d5391f1c8991aa9879c"

      define_method(:install) do
        bin.install "baywatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.10.0/baywatch_0.10.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ab0ccc9067431b298e71c8b97052b34b8e71b6d8d4747b0f09ef9fff3b7e8b66"
      define_method(:install) do
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.10.0/baywatch_0.10.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "406304ee7496726087f8db7216d84439550403f0e6f8d520552d9271ed729e0b"
      define_method(:install) do
        bin.install "baywatch"
      end
    end
  end

  def caveats
    <<~EOS
      Run 'baywatch dependencies' to install optional casks and cloud CLI extensions.
    EOS
  end
end
