# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v0180 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.18.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.18.0/baywatchdog_0.18.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "be135fc03cb25b3e60c9a8ae8708f48d238ebefabc8a3497b8c92f5f2ff15860"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.18.0/baywatchdog_0.18.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e2bac0a5dbe4a3b9ae96adaead1dd809f12d1545417662cdaef0e8dea4b3c5de"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.18.0/baywatchdog_0.18.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8b989c8761ae26b66606f94ede1a88b04d4210c50e67c7151e874a6310c4dcb3"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.18.0/baywatchdog_0.18.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "15bc751027a93af26e2dad5a387f89ceff602be0362473a1458c5401495ad353"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end
end
