# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class BaywatchAT052 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatch"
  version "0.5.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatch/releases/download/v0.5.2/baywatch_0.5.2_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "df9efa013abdef88ecb04c1e0b5a0cb2890df910654ef8d0f64ca651c4cbc897"

      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatch/releases/download/v0.5.2/baywatch_0.5.2_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b5b56857beff6901aafa44982eb44c92668c11916876777437a2de9fdd4c72ea"

      def install
        bin.install "baywatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.5.2/baywatch_0.5.2_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4f2aca659955ab93e7b05f6e5ba7c2b8896277ef2f0ab91d9c2b65d93ccb35a0"
      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.5.2/baywatch_0.5.2_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d08f57f7926f7a4f22001769f6e00bad78e323d320f58b32968db7aceedd2689"
      def install
        bin.install "baywatch"
      end
    end
  end
end
