# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v0326 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.32.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.32.6/baywatchdog_0.32.6_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "43da358cbb2ed9a590c92eee6773b72a01b3601297bd1c2999eebdb22b6fefec"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.32.6/baywatchdog_0.32.6_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "90d85ff63bb03cad8688cd3c5305bb99f0cf0cba833d6b7ac34656a5fe70c779"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.32.6/baywatchdog_0.32.6_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "eaf13a3bc05e6da912c20896e5e53d40ddff69cf636f0663a6b9f1f675e1ea2f"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.32.6/baywatchdog_0.32.6_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8c97621aa80e4b0d2955236ab376def755daec7c1c095b7b07010cc4e29aaad0"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end
end
