# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.9.0/baywatchdog_0.9.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "dd4937e816b59561b312f3ad5be05cc60535c4e1688c723e9b4211f462955ece"

      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.9.0/baywatchdog_0.9.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "18157459c72d17155f6ff733946180e76e6405f885a66444fba95c5e83dd26f7"

      def install
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.9.0/baywatchdog_0.9.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fa67bdb394ba0a97dbcda8ccab93a2aa68f4ffcfaa01b5ed986e4f79e75270d5"
      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.9.0/baywatchdog_0.9.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5147c830ec0eb61d181073818cda69d6e98d04ee2e3956fb7c4c03ad4ee6ea24"
      def install
        bin.install "baywatchdog"
      end
    end
  end
end
