# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.28.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.28.0/baywatchdog_0.28.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "12c1aea11590edcc782377155588ab8937704a85d9bd929bf5c681cc28a591b4"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.28.0/baywatchdog_0.28.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2138ef3a55dbb44f213ae67e7c08847469e3f6dc60e5aeaed5c60957f08a707f"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.28.0/baywatchdog_0.28.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "be529d37dadfb9fe502a6491c3754f9a7cedff8017fe5b66afc1015d9d5f1e5a"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.28.0/baywatchdog_0.28.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0763ac6074e6fc9f7f6ef6ffb523230bdf247c4275da595e5df6a7c40df84fdb"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end
end
