# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v060 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.6.0/baywatchdog_0.6.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "310e74766ccaf8d3dc2ab247e1901b89af39ee7baa233708e3390efb03e563e5"

      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.6.0/baywatchdog_0.6.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d4390138b53609932af1831ac305769af7842a8236418cde5a5977da33ca3aad"

      def install
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.6.0/baywatchdog_0.6.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "33ce72d771887e7ca43a91ae23c2c0166fc154300965ff2bff7f5b14b23d9145"
      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.6.0/baywatchdog_0.6.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c3cd8e3830b7e2a352e452a4a0e2c7263fd19402836ed7d693d568fa1f57e2e9"
      def install
        bin.install "baywatchdog"
      end
    end
  end
end
