# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v0323 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.32.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.32.3/baywatchdog_0.32.3_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b1f4ad4a163f068c27f6a0624873ccba2dfb1611070324938394262269533a19"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.32.3/baywatchdog_0.32.3_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c853ca9d71c785fa8d8a6c3fefc850755fc56619fcea7019d23a78d1c7aa4a53"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.32.3/baywatchdog_0.32.3_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0bdaed006364e63f56554a930803abde1c7cfefd2a4cafefe6274cf8b3821b96"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.32.3/baywatchdog_0.32.3_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6d96eb569397060c1fbecc7ed21174d309add4b0d4532afccefa6d807b6c6d18"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end
end
