# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v0253 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.25.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.25.3/baywatchdog_0.25.3_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4405102371c0b3e777432ea91c127eef98667a4f02747fe507a2e6872ff857f5"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.25.3/baywatchdog_0.25.3_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1b90319d0f88d0585a96f1f81467a87ad7a41adfad1a1104a910f51f752fb279"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.25.3/baywatchdog_0.25.3_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4f14804ccf45bf69e99b3b48eb477f1ce6b12accea5ddeb6eb117721ef06de37"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.25.3/baywatchdog_0.25.3_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d82e7cf41adf62d6c7dd6b3a14efb24ac7f0ce29168dfff6bfcb1b3ebebb9a55"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end
end
