# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v0160 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.16.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.16.0/baywatchdog_0.16.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e32b059e64bc67c24d707d3d241d300cec03bdef94309d5e5155aa86e46e3c73"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.16.0/baywatchdog_0.16.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ef7bca87899af19fa98151215d9c0c33effadf4578495e48848c1ff8dced3110"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.16.0/baywatchdog_0.16.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1c404d964605b9311eb3a8df7eee846366fbb387d0bbc5dbeb7b08f56fb04123"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.16.0/baywatchdog_0.16.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "56380bc3f218cf1f3e6c5a3f87a04da0ab572fad9de51f58429c69d0c0294150"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end
end
