# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class BaywatchAT070 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatch"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatch/releases/download/v0.7.0/baywatch_0.7.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "92b835f2785f4f7a8d71a5034520a3541c236e9f698ba603731783d06826248e"

      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatch/releases/download/v0.7.0/baywatch_0.7.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fd516d0d55b8942997f0b9f93c63757d58c3f0be468ef862beba8548d2a50fac"

      def install
        bin.install "baywatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.7.0/baywatch_0.7.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1dd6677ecb8900a472ab0e6a82934c27da4092b9b03f280c83df986357bb9600"
      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.7.0/baywatch_0.7.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8301ed83c5c892faae67ad4443e8f101b152446651f9ecd95df4fceed23b7dcb"
      def install
        bin.install "baywatch"
      end
    end
  end
end
