# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v0161 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.16.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.16.1/baywatchdog_0.16.1_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "80c0750023340ee10de817d63d41923b5f10fd07e5dc217bad6d66cad0bc8921"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.16.1/baywatchdog_0.16.1_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "279dd48190827d46fa5049d6e201ab360a7c718d9339f09958ac9c3630801606"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.16.1/baywatchdog_0.16.1_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d92737f6ac5f81bea40e39b879aa2c8eccae5ae92468eeda2dc0e9fbcf69865a"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.16.1/baywatchdog_0.16.1_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fa0949bd0c790bb8ba635c34b78e0e82d389ed16cf9ad066faf7f51b4cf0ee5a"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end
end
