# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.15.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.15.1/baywatchdog_0.15.1_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d1d483ea1232127e3489eaa3cec05b81fe1ce86bc044fe8937dd52a8d3d3dbe9"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.15.1/baywatchdog_0.15.1_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e1125004c22ec8b02cde7eaf665884f76b4e163435e7027cb5713ba8aec9620b"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.15.1/baywatchdog_0.15.1_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8eb349dd583c2948e9b9ca419852b66ade6697963e44d043a6afe47c5102bf54"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.15.1/baywatchdog_0.15.1_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fc07bf74d2116e339c2e0c5768ecf8936008585dc1e2635519eba245b6b14e0b"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end
end
