# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class BaywatchAT080 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatch"
  version "0.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatch/releases/download/v0.8.0/baywatch_0.8.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c7b29083764e681c89aa86c80804d77a70f17ecabb2ef944cf667e2a9dba676d"

      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatch/releases/download/v0.8.0/baywatch_0.8.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5006d2e433a4708e35c35cbfc01dcc7a54a670dfe366339c4ff1ff87b8029b0a"

      def install
        bin.install "baywatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.8.0/baywatch_0.8.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e625f56aca4cc6b6d809c6c9c319a987928ecf87429751a9a53aec2f6b2f7b81"
      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.8.0/baywatch_0.8.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0f8ac411ef2235f5344524d37636840263fc7bc9c9d5efbe59cd552605ef06da"
      def install
        bin.install "baywatch"
      end
    end
  end
end
