# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v0130 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.13.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.13.0/baywatchdog_0.13.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "dc74c4ee98fa0e011ca600f02cc2404d93e5aa364b7148ed597de2c7bd41ac9c"

      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.13.0/baywatchdog_0.13.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6df62de33de308dd23086b1ad8303688e307ec33e5d111a16f3f8399e9197b9c"

      def install
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.13.0/baywatchdog_0.13.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a4d4008cf14d606b79ac2cc0be902e56423cff03dfd227c95a3ab20f841191bf"
      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.13.0/baywatchdog_0.13.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c6caf6f3061ed2f6dfbb8252d180c65b41fc353f2e2fddb274d4106ca126ee40"
      def install
        bin.install "baywatchdog"
      end
    end
  end
end
