# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v091 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.9.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.9.1/baywatchdog_0.9.1_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "10c608e40dde1886f2883e40156e1b5fe4bad48c6200cbd4c9990c18b5429a24"

      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.9.1/baywatchdog_0.9.1_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d8b95380d379c79484569b14de3721696f0a02b9d90ac9960956741dd6a99644"

      def install
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.9.1/baywatchdog_0.9.1_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b56b541001c62d5f52e8ced115eeaf92a9eacc6d9a4f501ea55d63cc955ce4ae"
      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.9.1/baywatchdog_0.9.1_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "28c5ce813607abd6a7330b92ce60c56e902e00d666341c7255340857e517e715"
      def install
        bin.install "baywatchdog"
      end
    end
  end
end
