# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v0100 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.10.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.10.0/baywatchdog_0.10.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f3216337811b7cec60841811d5c9924f44399ea6611cb2b9257710cf01d1fc74"

      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.10.0/baywatchdog_0.10.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "01ba3b7924901ad8cb6b1f8744eb726438a124e90de689173e2f8aa055ebc645"

      def install
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.10.0/baywatchdog_0.10.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "60834395e53dd5b73f1875c5c72077deb1eeb4183dc1d2798f9b89027b558a8b"
      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.10.0/baywatchdog_0.10.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c5a802a3a760d7aeefff8da31db2e5c5c99b7e744e25ba2a8e4de49481496411"
      def install
        bin.install "baywatchdog"
      end
    end
  end
end
