# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class BaywatchAT022 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatch"
  version "0.2.2"

  on_macos do
    on_intel do
      url "https://github.com/padok-team/baywatch/releases/download/v0.2.2/baywatch_0.2.2_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "bda90d1e6a49de3f079b8804a6ab5fe68c21d94aa22761cac3d3e1af89112d2e"

      def install
        bin.install "baywatch"
      end
    end
    on_arm do
      url "https://github.com/padok-team/baywatch/releases/download/v0.2.2/baywatch_0.2.2_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "572a0336daa84a27818f7f066315b279822c38ab08ba2bb91d545f584b13fec1"

      def install
        bin.install "baywatch"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/padok-team/baywatch/releases/download/v0.2.2/baywatch_0.2.2_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "0bb371b4bd14aef27d4430d15a8840f8d1e5c384d5813184287e3fb71f247106"

        def install
          bin.install "baywatch"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/padok-team/baywatch/releases/download/v0.2.2/baywatch_0.2.2_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "064a42d9f8fb8ab396903c5c76fd9693b83ad48c4ef0a8084a4df84002cf3dd4"

        def install
          bin.install "baywatch"
        end
      end
    end
  end
end
