# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v050 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.5.0/baywatchdog_0.5.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e8d0a435dff665c6d888e89c834b43b21bcb85913d189e14c5ba7513c74ae4dc"

      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.5.0/baywatchdog_0.5.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e8973853d33acdf8775d13e12c32ff6998b0ce80d5181555217969a6a12e5996"

      def install
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.5.0/baywatchdog_0.5.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d1ce38c7445f5f27506182efd92a95281dd40cc4f3216330dcd0d007ec482c4c"
      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.5.0/baywatchdog_0.5.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "cab36821deed75f611489ed6340cad2471fb01404743585d4220e65d50db7b0b"
      def install
        bin.install "baywatchdog"
      end
    end
  end
end
