# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v0210 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.21.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.21.0/baywatchdog_0.21.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4e9403f305d1f238e4901970cc23f1dd26744a2d9a49e240a722cc90641b7cb6"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.21.0/baywatchdog_0.21.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3714293bd57e19d81358e72cae58c4db88c00c5d38b7a2571f4488c7830adfee"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.21.0/baywatchdog_0.21.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "70d04d3b10a595fb37bf940b4ae20a0293d8f2cfed9404f5ffa61a7ddbcdf813"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.21.0/baywatchdog_0.21.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "10870393c75829e47943f22852f95d98fdd1b5ddf2ab5f44b7aed07c29808f63"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end
end
