# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class BaywatchAT082 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatch"
  version "0.8.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatch/releases/download/v0.8.2/baywatch_0.8.2_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "15c969afdb023e4be190667ceff5a77e63ffec55a694930a3f0ac157cd0b2449"

      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatch/releases/download/v0.8.2/baywatch_0.8.2_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4f32cf570837f24cdd558ac7eda1780fcdb08f60866de318282db6bab362244c"

      def install
        bin.install "baywatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.8.2/baywatch_0.8.2_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "61f6a1bdf6bb9d9b6850fb292ffd4e92e380f3592858977f712d54341674a805"
      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.8.2/baywatch_0.8.2_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "29789c1b510e0ae830952f6b4805fec8b365e84cdb20113649b65d067358c797"
      def install
        bin.install "baywatch"
      end
    end
  end
end
