# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v070 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.7.0/baywatchdog_0.7.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3e982c8435f4f9f5f510b65f50b8803047fc3e7572d30975164dea351337c826"

      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.7.0/baywatchdog_0.7.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e572f2d18f057feabe3a2e35478a71657b615c5a1a419ee4bee7584f18e6bf4d"

      def install
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.7.0/baywatchdog_0.7.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "401bb2f09ff807a82bcde4c80d659d2130a6661223f61a07b47d3ae350bc99a7"
      def install
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.7.0/baywatchdog_0.7.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f5015d25b260a635c9fd7ef00ddab2c4d76d615a64e8e4e937f57047f1e5ac86"
      def install
        bin.install "baywatchdog"
      end
    end
  end
end
