# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class BaywatchAT012 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatch"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatch/releases/download/v0.1.2/baywatch_0.1.2_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "418ed76917f84670034cfd07475545329280979c6f45de2661ec41748d1395e0"

      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatch/releases/download/v0.1.2/baywatch_0.1.2_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9ef93e4599c1c5af7675d6a4c66126030eb00020f3bc0beeb9651dbdb36ab665"

      def install
        bin.install "baywatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.1.2/baywatch_0.1.2_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "bec31dc74feff4c277ffcd4d13ad937f9e12cfb1929d2333454f5ea7bdaa455f"

      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatch/releases/download/v0.1.2/baywatch_0.1.2_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2dd67972b932c9243b1d3cd88481cab3445d5a75b8c69c416d9528a263a83688"

      def install
        bin.install "baywatch"
      end
    end
  end
end
