# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatchdog@v0230 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatchdog"
  version "0.23.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.23.0/baywatchdog_0.23.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5234a37db0eb49af019499d2cda4e828b885f2e2c15af4237021d8c4a2d091fb"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.23.0/baywatchdog_0.23.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "275f28b08185479efcc79b9442fd0a8cb4c79a74e5f39b2cacda307166036260"

      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.23.0/baywatchdog_0.23.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "249c571587934c4f97d6db4c7659158abe435c5b2087ce4dd1d3a8d6a24ed967"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatchdog/releases/download/v0.23.0/baywatchdog_0.23.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "30f0aae02b75bd2890e5e26314582f8bb7707ff176435e0ae9b14d4979bc5a4e"
      define_method(:install) do
        bin.install "baywatchdog"
      end
    end
  end
end
