# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatch < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatch"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatch/releases/download/v0.1.5/baywatch_0.1.5_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fd15d3d3f8bad58377e8aa6590e35bfd6896e9c3dde2b90e9fdc393fc66bb6af"

      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatch/releases/download/v0.1.5/baywatch_0.1.5_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9941aeb6222711c478425bbb866fc628aecc7b3e024f886e49e8bd7ec7bb8006"

      def install
        bin.install "baywatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatch/releases/download/v0.1.5/baywatch_0.1.5_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b4e7aedd845b2e7fa76083ffba71313c981a881c5613474c0355969ecaf246ad"

      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.1.5/baywatch_0.1.5_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "89b82edcfc95933e8f10daab2bd82b57d3f3765f6d897771f22ee04c296102a1"

      def install
        bin.install "baywatch"
      end
    end
  end
end
