# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Baywatch < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatch"
  version "0.10.1"

  depends_on "aws-vault"
  depends_on "awscli"
  depends_on "azure-cli"
  depends_on "jq"
  depends_on "kubernetes-cli"
  depends_on "scw"
  depends_on "sshuttle"
  depends_on "yq"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatch/releases/download/v0.10.1/baywatch_0.10.1_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4e41cd2cde1cce33afe00ccc7f3110693270dba88b93f09ffcd5bdd64b33c027"

      define_method(:install) do
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatch/releases/download/v0.10.1/baywatch_0.10.1_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "90387fbe669ecdf312d9e7706e44b2fa6ff85d59b7fd92acd1656f6944bf3c17"

      define_method(:install) do
        bin.install "baywatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.10.1/baywatch_0.10.1_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "973a7dcc20c0e73489b3a2b16ae79dc8de5807280fc26635d309a6f27fa08124"
      define_method(:install) do
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.10.1/baywatch_0.10.1_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9b3fde397efb97b720c811a89f46e301d9d92a8607397f6061e9541e783b9ee3"
      define_method(:install) do
        bin.install "baywatch"
      end
    end
  end

  def caveats
    <<~EOS
      Run 'baywatch dependencies' to install optional casks and cloud CLI extensions.
    EOS
  end
end
