# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class BaywatchAT018 < Formula
  desc ""
  homepage "https://github.com/padok-team/baywatch"
  version "0.1.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatch/releases/download/v0.1.8/baywatch_0.1.8_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "09cd8534216962f3e43fb83d01da8b5ddcc68beb50fa149f20a22e1e5f819ac9"

      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/baywatch/releases/download/v0.1.8/baywatch_0.1.8_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1bf86041775694ff5ca052f9ca1b25c07da408faad54f44b3e5ef792330df61e"

      def install
        bin.install "baywatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/baywatch/releases/download/v0.1.8/baywatch_0.1.8_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2e1550f9527ec27d489f3c6bc9054c09297cbf022368647776280ae4d7cb9162"

      def install
        bin.install "baywatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/baywatch/releases/download/v0.1.8/baywatch_0.1.8_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "de528adafa90ba1a173bc467914ff005e3e9db345b157c4105da02cd7a43f8d0"

      def install
        bin.install "baywatch"
      end
    end
  end
end
