# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSecretScannerATV050 < Formula
  desc ""
  homepage "https://github.com/padok-team/git-secret-scanner"
  version "0.5.0"

  on_macos do
    on_intel do
      url "https://github.com/padok-team/git-secret-scanner/releases/download/v0.5.0/git-secret-scanner_0.5.0_darwin_amd64.tar.gz"
      sha256 "1a27f67e82e97f40b85d57ef5a23feda442da9b786c703663f56fc2d6ab17cd8"

      def install
        bin.install "git-secret-scanner"
      end
    end
    on_arm do
      url "https://github.com/padok-team/git-secret-scanner/releases/download/v0.5.0/git-secret-scanner_0.5.0_darwin_arm64.tar.gz"
      sha256 "94fcf7397e537716943aa7dbd427d42fe98b62db11707fadb099b0962d0e0016"

      def install
        bin.install "git-secret-scanner"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/padok-team/git-secret-scanner/releases/download/v0.5.0/git-secret-scanner_0.5.0_linux_amd64.tar.gz"
        sha256 "328fd37909535fc3ed25928ec3da602c1a2fe473b4045118c1b251d94a3fa214"

        def install
          bin.install "git-secret-scanner"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/padok-team/git-secret-scanner/releases/download/v0.5.0/git-secret-scanner_0.5.0_linux_arm64.tar.gz"
        sha256 "bfc3af32ee79a584d1e0a2968f9b615c716c9e01f61ceaf9e7bdf39251ba8e5f"

        def install
          bin.install "git-secret-scanner"
        end
      end
    end
  end
end
