# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSecretScanner < Formula
  desc ""
  homepage "https://github.com/padok-team/git-secret-scanner"
  version "0.5.1"

  on_macos do
    on_intel do
      url "https://github.com/padok-team/git-secret-scanner/releases/download/v0.5.1/git-secret-scanner_0.5.1_darwin_amd64.tar.gz"
      sha256 "39e00cf9f74814c194c774a35678d7497d14a30c22799c4e2c2e37d18587f073"

      def install
        bin.install "git-secret-scanner"
      end
    end
    on_arm do
      url "https://github.com/padok-team/git-secret-scanner/releases/download/v0.5.1/git-secret-scanner_0.5.1_darwin_arm64.tar.gz"
      sha256 "bf9924b204cc77c7d2ccc47c1e992773b945b0c31c7c32a19b93ce87615f0988"

      def install
        bin.install "git-secret-scanner"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/padok-team/git-secret-scanner/releases/download/v0.5.1/git-secret-scanner_0.5.1_linux_amd64.tar.gz"
        sha256 "b4e49d6c57331a994e840d2178905e846d8f143874bd0f2affab174b824ae5b6"

        def install
          bin.install "git-secret-scanner"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/padok-team/git-secret-scanner/releases/download/v0.5.1/git-secret-scanner_0.5.1_linux_arm64.tar.gz"
        sha256 "c818c61d9e05e3ede2f5f403dd377536887b7237038dd1f93bc363a8a05708f5"

        def install
          bin.install "git-secret-scanner"
        end
      end
    end
  end
end
