# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSecretScanner < Formula
  desc ""
  homepage "https://github.com/padok-team/git-secret-scanner"
  version "0.5.1"

  on_macos do
    on_intel do
      url "https://github.com/padok-team/git-secret-scanner/releases/download/v0.5.1/git-secret-scanner_0.5.1_darwin_amd64.tar.gz"
      sha256 "1175bc84b806ab66f433c142067ade6117099bda55a6fc3a8e1fd720078a295c"

      def install
        bin.install "git-secret-scanner"
      end
    end
    on_arm do
      url "https://github.com/padok-team/git-secret-scanner/releases/download/v0.5.1/git-secret-scanner_0.5.1_darwin_arm64.tar.gz"
      sha256 "2fbe1114ec4a762b7cb8784b99bddb6791879226792b6f713c0dcb7aa2fb5978"

      def install
        bin.install "git-secret-scanner"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/padok-team/git-secret-scanner/releases/download/v0.5.1/git-secret-scanner_0.5.1_linux_amd64.tar.gz"
        sha256 "0b2b390b6c3f36a6322500d9f02957f5314c4b0c4e848deb62de4e152239f444"

        def install
          bin.install "git-secret-scanner"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/padok-team/git-secret-scanner/releases/download/v0.5.1/git-secret-scanner_0.5.1_linux_arm64.tar.gz"
        sha256 "465890c09dfaa6ec38e36564cd33d0214b53c66213c567156b14770cc9b21d32"

        def install
          bin.install "git-secret-scanner"
        end
      end
    end
  end
end
