# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSecretScanner < Formula
  desc ""
  homepage "https://github.com/padok-team/git-secret-scanner"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/git-secret-scanner/releases/download/v0.6.0/git-secret-scanner_0.6.0_darwin_amd64.tar.gz"
      sha256 "5c0576fd489e54db0595527dae8a3b7e036552fec853bb05be604732f1ed7f99"

      def install
        bin.install "git-secret-scanner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/git-secret-scanner/releases/download/v0.6.0/git-secret-scanner_0.6.0_darwin_arm64.tar.gz"
      sha256 "13d2ae637121a54bb0770c5e6dbc072825be2b9fa5e11cabadc61f615427df88"

      def install
        bin.install "git-secret-scanner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/git-secret-scanner/releases/download/v0.6.0/git-secret-scanner_0.6.0_linux_amd64.tar.gz"
      sha256 "5937458fe0431dc07e054314aaaf4b043c9d793315a2b9890c280d7ade684355"
      def install
        bin.install "git-secret-scanner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/git-secret-scanner/releases/download/v0.6.0/git-secret-scanner_0.6.0_linux_arm64.tar.gz"
      sha256 "96b6dd8fcd4fe314140d9734b2c20f1424f7936203fa929217a2e16187666298"
      def install
        bin.install "git-secret-scanner"
      end
    end
  end
end
