# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GuacamoleAT020 < Formula
  desc ""
  homepage "https://github.com/padok-team/guacamole"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/guacamole/releases/download/v0.2.0/guacamole_0.2.0_darwin_amd64.tar.gz"
      sha256 "3ad12995de2103e6502cb407893a976de4ffcf20beb027142b3bdc658acabd20"

      def install
        bin.install "guacamole"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/guacamole/releases/download/v0.2.0/guacamole_0.2.0_darwin_arm64.tar.gz"
      sha256 "74d93b8115e5ab5f5e3c629b3652f11f0395ace30d0997273cd8b302c9b8a4d6"

      def install
        bin.install "guacamole"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/guacamole/releases/download/v0.2.0/guacamole_0.2.0_linux_amd64.tar.gz"
      sha256 "e2cad958890c4f720edd0cd1fa28fd830cac78e5480e9c18d609096965dd7daf"

      def install
        bin.install "guacamole"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/guacamole/releases/download/v0.2.0/guacamole_0.2.0_linux_arm64.tar.gz"
      sha256 "88c15e4cad25f502834600e73114c91591dfc2c99263a5e66e2fc08fdc0841a4"

      def install
        bin.install "guacamole"
      end
    end
  end
end
