# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GuacamoleAT031 < Formula
  desc ""
  homepage "https://github.com/padok-team/guacamole"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/guacamole/releases/download/v0.3.1/guacamole_0.3.1_darwin_amd64.tar.gz"
      sha256 "c388681787be24b602832f42efcc49f39d57a94f9d1da615a5372609356402a0"

      def install
        bin.install "guacamole"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/guacamole/releases/download/v0.3.1/guacamole_0.3.1_darwin_arm64.tar.gz"
      sha256 "1b0e1a28315ae0334194b9382e75c4b1597c8fbaac8b50754e243bb01af4035a"

      def install
        bin.install "guacamole"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/padok-team/guacamole/releases/download/v0.3.1/guacamole_0.3.1_linux_amd64.tar.gz"
        sha256 "a7cd8df8e2d2af9ed6f6466067d1fd690f0806fe0c4c3e20861d9725ba9a2636"

        def install
          bin.install "guacamole"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/padok-team/guacamole/releases/download/v0.3.1/guacamole_0.3.1_linux_arm64.tar.gz"
        sha256 "9c58d3e0a585ac15fc2e1ddffbfd67f00203485e44f6dffed4eed946bc6b4fa7"

        def install
          bin.install "guacamole"
        end
      end
    end
  end
end
