# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class GuacamoleAT010 < Formula
  desc ""
  homepage "https://github.com/padok-team/guacamole"
  version "0.1.0-rc14"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/guacamole/releases/download/v0.1.0-rc14/guacamole_0.1.0-rc14_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0e45f51dc1eda594ee01ae790c34ad9b11dde478e20beacaf22c24f74ca413e0"

      def install
        bin.install "guacamole"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/guacamole/releases/download/v0.1.0-rc14/guacamole_0.1.0-rc14_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7c71f220acfb79320a607b746d400de61d4869269dd3adedca08e7c1f1176987"

      def install
        bin.install "guacamole"
      end
    end
  end
end
