# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Guacamole < Formula
  desc ""
  homepage "https://github.com/padok-team/guacamole"
  version "0.1.0-rc4"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/guacamole/releases/download/v0.1.0-rc4/guacamole_0.1.0-rc4_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b1fb5d330d2d7cf3c6ae064c90418325ece17a357927108325cd23d6f7b603da"

      def install
        bin.install "guacamole"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/guacamole/releases/download/v0.1.0-rc4/guacamole_0.1.0-rc4_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "cd0607ba4b2481364759c0b0980ebc08fab1d75bacdae8ba6126449c1b3d9502"

      def install
        bin.install "guacamole"
      end
    end
  end
end
