# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Guacamole < Formula
  desc ""
  homepage "https://github.com/padok-team/guacamole"
  version "1.3.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/guacamole/releases/download/v1.3.3/guacamole_1.3.3_darwin_amd64.tar.gz"
      sha256 "6f81d410bbe008129e120a51dae2fa2fffaf7aa7d5ef343b6a7130a953a03af2"

      def install
        bin.install "guacamole"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/guacamole/releases/download/v1.3.3/guacamole_1.3.3_darwin_arm64.tar.gz"
      sha256 "9de5da52a4cfa527a3c44b98ac1fdc5f1dc98cd7be21b09899893f2fce135f45"

      def install
        bin.install "guacamole"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/guacamole/releases/download/v1.3.3/guacamole_1.3.3_linux_amd64.tar.gz"
      sha256 "015f9278467ec928404f5e96caaf9ba048e31ebefdf7c8f8b9daa5bc2ea68285"
      def install
        bin.install "guacamole"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/guacamole/releases/download/v1.3.3/guacamole_1.3.3_linux_arm64.tar.gz"
      sha256 "7eb61c53c0f074b89e01402c1d6c24ac048cca6329611c23f93002ecb47b715b"
      def install
        bin.install "guacamole"
      end
    end
  end
end
