# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class GuacamoleAT < Formula
  desc ""
  homepage "https://github.com/padok-team/guacamole"
  version "0.1.0-rc10"
  depends_on :linux

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/guacamole/releases/download/v0.1.0-rc10/guacamole_0.1.0-rc10_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b36c4edb37f8277fa92accdf9b2c65a1e8b45b52196d0f046f9ef08b8f05d4b8"

      def install
        bin.install "guacamole"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/guacamole/releases/download/v0.1.0-rc10/guacamole_0.1.0-rc10_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0eba527d35974342fdfea9f2575fbfebe6d6ded472437733b7100ec8a1209647"

      def install
        bin.install "guacamole"
      end
    end
  end
end
