# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GuacamoleAT034 < Formula
  desc ""
  homepage "https://github.com/padok-team/guacamole"
  version "0.3.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/guacamole/releases/download/v0.3.4/guacamole_0.3.4_darwin_amd64.tar.gz"
      sha256 "6e2c49122a5238517d28bde5abaa36ea2c3a963a35afc5a010d2a725a503eec2"

      def install
        bin.install "guacamole"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/guacamole/releases/download/v0.3.4/guacamole_0.3.4_darwin_arm64.tar.gz"
      sha256 "2b814cd03fc973b8957922c2909b43ffd34f8b13bc359e827a7822bfafd7e49e"

      def install
        bin.install "guacamole"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/guacamole/releases/download/v0.3.4/guacamole_0.3.4_linux_amd64.tar.gz"
      sha256 "95a50cbf10bbdf58c231fc58f27f0f2d400252ad6cab5088f298051a747d1ae4"
      def install
        bin.install "guacamole"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/guacamole/releases/download/v0.3.4/guacamole_0.3.4_linux_arm64.tar.gz"
      sha256 "e25b9472efd2279dd3f29bec584870519f291ca9a2a0f60f07e209e16596499c"
      def install
        bin.install "guacamole"
      end
    end
  end
end
