# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GuacamoleAT134 < Formula
  desc ""
  homepage "https://github.com/padok-team/guacamole"
  version "1.3.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/guacamole/releases/download/v1.3.4/guacamole_1.3.4_darwin_amd64.tar.gz"
      sha256 "df9af1fdf195f70c467687e95e9a18c4f343749e04518170f62b235290e6bed8"

      def install
        bin.install "guacamole"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/guacamole/releases/download/v1.3.4/guacamole_1.3.4_darwin_arm64.tar.gz"
      sha256 "4723965cbc28fdbb7128ee7663893cc5680b8730aa52f82c2db06939db5254a8"

      def install
        bin.install "guacamole"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/guacamole/releases/download/v1.3.4/guacamole_1.3.4_linux_amd64.tar.gz"
      sha256 "44eade1986151419010c3c7695142573ea293df068c881d6f4a0cfbbecfee484"
      def install
        bin.install "guacamole"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/guacamole/releases/download/v1.3.4/guacamole_1.3.4_linux_arm64.tar.gz"
      sha256 "a0f4920a6926f7e116845199782bc20c36c804dd8b8e112ef3f8ff843bee4646"
      def install
        bin.install "guacamole"
      end
    end
  end
end
