# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Playground < Formula
  desc "Use the padok playground"
  homepage "https://github.com/padok-team/playground"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/playground/releases/download/v0.1.1/playground_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1780ef08a1a991aa3267232a4de9f9484935b5ffe59fc0b06fb0a22594548e4e"

      def install
        bin.install "playground"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/playground/releases/download/v0.1.1/playground_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "965fc3baf0f5d3e8fd60cd934c1e66e01ba9a3afbf04f0ceaac5a1bcffb53de3"

      def install
        bin.install "playground"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/playground/releases/download/v0.1.1/playground_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9ae668501bedeb631b47e7acb4b5f106db9cf8830c43fa8200189745a03c5dea"

      def install
        bin.install "playground"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/playground/releases/download/v0.1.1/playground_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "248add41a9539285a95d1ea378d3ea1d96b15252b1513e3c7f9b85abb54a4a3b"

      def install
        bin.install "playground"
      end
    end
  end
end
