# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Playground < Formula
  desc "Use the padok playground"
  homepage "https://github.com/padok-team/playground"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/playground/releases/download/v0.1.1/playground_Darwin_arm64.tar.gz"
      sha256 "da7f4830b94fe360709e5263decbc39fa3229dce0541a501623cfc8895b3b9ad"

      def install
        bin.install "playground"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/playground/releases/download/v0.1.1/playground_Darwin_x86_64.tar.gz"
      sha256 "ee93fbc09382083811135b6101a7d639aabf1c8e5ba5c81bb398a178b654a5e6"

      def install
        bin.install "playground"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/playground/releases/download/v0.1.1/playground_Linux_arm64.tar.gz"
      sha256 "5f5ba75aefc1060799745b12604c3cafdb6b9c1fc66404c11f80e19fb8545a60"

      def install
        bin.install "playground"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/playground/releases/download/v0.1.1/playground_Linux_x86_64.tar.gz"
      sha256 "5802fd524e1cfc2ac13aae2d128383cfb6e168de38f2b65f3ad28730285a9f0f"

      def install
        bin.install "playground"
      end
    end
  end
end
