# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Playground < Formula
  desc "Use the padok playground"
  homepage "https://github.com/padok-team/playground"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/playground/releases/download/v0.1.1/playground_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e5f4029004a6c46a5e906021f7ca515e7730dfce65e7a4481a3076fbc88d8388"

      def install
        bin.install "playground"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/playground/releases/download/v0.1.1/playground_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2a197b0fca24e7a67182f9886abd34325f20ad787038d7846099b586e57f59c2"

      def install
        bin.install "playground"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/playground/releases/download/v0.1.1/playground_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "734e4fca2858bdc2fc69f08f9a565d92f15aa6a3b8f76b35f1af9ef3b45e26c9"

      def install
        bin.install "playground"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/playground/releases/download/v0.1.1/playground_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "072a7462fd4685b81cf0ac434888e04ad6ae378205283210198ad47d28ea0d33"

      def install
        bin.install "playground"
      end
    end
  end
end
