# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfautomv < Formula
  desc "Generate Terraform moved blocks automatically for painless refactoring"
  homepage "https://github.com/padok-team/tfautomv"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/tfautomv/releases/download/v0.4.0/tfautomv_0.4.0_Darwin_arm64.tar.gz"
      sha256 "1a09ad65ed3c292a9928f5bfceaecca9601ed218c013b637e3af3fafa9a6a6cb"

      def install
        bin.install "tfautomv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/tfautomv/releases/download/v0.4.0/tfautomv_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "2891e484a91480b9cca049d0415e1e8d307c1f0217ed7171097c317294b75098"

      def install
        bin.install "tfautomv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/tfautomv/releases/download/v0.4.0/tfautomv_0.4.0_Linux_arm64.tar.gz"
      sha256 "9c719a9ac19ba0de477d411a1ac692e6579dfbe910612f94fbed24541ccfaf8e"

      def install
        bin.install "tfautomv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/tfautomv/releases/download/v0.4.0/tfautomv_0.4.0_Linux_x86_64.tar.gz"
      sha256 "c45a776469dbbe5fa27b3fd84d1d8f0d056919394156541f3e89c3d40802d244"

      def install
        bin.install "tfautomv"
      end
    end
  end

  test do
    system "#{bin}/tfautomv -version"
  end
end
