# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfautomv < Formula
  desc "Generate Terraform moved blocks automatically for painless refactoring"
  homepage "https://github.com/padok-team/tfautomv"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/tfautomv/releases/download/v0.3.1/tfautomv_0.3.1_Darwin_arm64.tar.gz"
      sha256 "9eda85432822109f4322c05dda6185107e9e171a72dbd8526aee63e14af521f9"

      def install
        bin.install "tfautomv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/tfautomv/releases/download/v0.3.1/tfautomv_0.3.1_Darwin_x86_64.tar.gz"
      sha256 "e5d8331cd2eb3078cd2678971c0bb527a809634ef8f3909788db5854da28eb53"

      def install
        bin.install "tfautomv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/tfautomv/releases/download/v0.3.1/tfautomv_0.3.1_Linux_arm64.tar.gz"
      sha256 "c76147ba1f3fe7a6b92ac9cf5bc83197759c2be3240112b75c7b7463c182ef99"

      def install
        bin.install "tfautomv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/tfautomv/releases/download/v0.3.1/tfautomv_0.3.1_Linux_x86_64.tar.gz"
      sha256 "a53f5e7e06f6f380ad2ef3fd18ee214963f2bcb6e7c02895b894985a8b3a6228"

      def install
        bin.install "tfautomv"
      end
    end
  end

  test do
    system "#{bin}/tfautomv -version"
  end
end
