# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yatas < Formula
  desc ""
  homepage "https://github.com/padok-team/yatas"
  version "1.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/yatas/releases/download/v1.5.1/yatas_1.5.1_Darwin_x86_64.tar.gz"
      sha256 "db714bbf5e248445d0284d61b94b8b2a7d6f424c613afec16a548dcbfa35bcfb"

      def install
        bin.install "yatas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/yatas/releases/download/v1.5.1/yatas_1.5.1_Darwin_arm64.tar.gz"
      sha256 "6c4348d578ea8a6d27139578721c93f6d02533fbc48aa1f8014f7cf82ae90006"

      def install
        bin.install "yatas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/yatas/releases/download/v1.5.1/yatas_1.5.1_Linux_arm64.tar.gz"
      sha256 "2e644d3e879b73e071f9a5194a6a4050394a95fc88bda78d6ca8480b149ecce6"

      def install
        bin.install "yatas"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/yatas/releases/download/v1.5.1/yatas_1.5.1_Linux_x86_64.tar.gz"
      sha256 "5e3b75096c6d38c7a61486c157d05c6a2703492c0713fdd5313ca2b2ab9a1439"

      def install
        bin.install "yatas"
      end
    end
  end
end
