# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yatas < Formula
  desc ""
  homepage "https://github.com/padok-team/yatas"
  version "1.3.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/YATAS/releases/download/v1.3.3/YATAS_1.3.3_Darwin_x86_64.tar.gz"
      sha256 "839fdf5b117c199df9ef72bb7615bf19dcc4114d0630a69204c32c3852f02174"

      def install
        bin.install "yatas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padok-team/YATAS/releases/download/v1.3.3/YATAS_1.3.3_Darwin_arm64.tar.gz"
      sha256 "b1ff3ed923b7fd15dc3e40638acf0fd499aef6d8163a9cab1cab2a11a3fcc9a5"

      def install
        bin.install "yatas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padok-team/YATAS/releases/download/v1.3.3/YATAS_1.3.3_Linux_arm64.tar.gz"
      sha256 "fc04688cd43f5ee55512bc6680318bf2a555964d4184d5901c68ac4251ee7f08"

      def install
        bin.install "yatas"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/padok-team/YATAS/releases/download/v1.3.3/YATAS_1.3.3_Linux_x86_64.tar.gz"
      sha256 "c05297adf43c598aad24d6ff2acc00b900012c732d66c0dae83e8a7dcaef83f6"

      def install
        bin.install "yatas"
      end
    end
  end
end
